services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: abc123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - elk-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-pabc123"]
      interval: 5s
      retries: 30
      start_period: 10s

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - mysql
    expose:
      - "8000"
    networks:
      - elk-net

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    depends_on:
      - app
    networks:
      - elk-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - apache
    ports:
      - "80:80"
    networks:
      - elk-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
    networks:
      - elk-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    networks:
      - elk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk-net

volumes:
  mysql_data:

networks:
  elk-net:
    driver: bridge
