version: '3.9'

services:
  holamundo:
    build: ./app_holamundo
    ports:
      - "8080:80"

  adiosmundo:
    build: ./app_adiosmundo
    ports:
      - "8081:80"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  apache:
    image: httpd:2.4
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "8082:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8083:80"
