version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3306:3306"

  holamundo:
    build:
      context: ./app_holamundo
    container_name: app_holamundo
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: loginapp

  adiosmundo:
    build:
      context: ./app_adiosmundo
    container_name: app_adiosmundo
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: loginapp

  apache:
    build:
      context: ./apache
    container_name: apache_reverse
    restart: unless-stopped
    depends_on:
      - holamundo
      - adiosmundo
    ports:
      - "8080:80"

  nginx:
    build:
      context: ./nginx
    container_name: nginx_reverse
    restart: unless-stopped
    depends_on:
      - holamundo
      - adiosmundo
    ports:
      - "80:80"
