
services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: abc123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - mysql
    expose:
      - "8000"  # FastAPI corre en 8000 dentro del contenedor

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "8080:8080"  # Apache escucha en 8080

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - apache
    ports:
      - "80:80"

volumes:
  mysql_data:
